### ISSUE TITLE
Missing index.js in dialects directory

### ISSUE THREAD

**Issue by puzzle-it-nu** [knex/knex#5706]
# Environment

Knex version: 3.0.0
Database + version: postgres 15
OS: linux fedora 38

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug
Running vitest with the new knex 3.0.0 fails while the same test works with 2.5.1

2. Error message
`
❯ api/getSessionData/getSessionData.test.js  (0 test)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  api/getSessionData/getSessionData.test.js [ api/getSessionData/getSessionData.test.js ]
Error: Cannot find module '../../dialects'
Require stack:
- /home/user/dev/gb/gbweb/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /home/user/dev/gb/gbweb/node_modules/knex/lib/knex-builder/Knex.js
- /home/user/dev/gb/gbweb/node_modules/knex/lib/index.js
 ❯ Object.<anonymous> node_modules/knex/lib/knex-builder/internal/config-resolver.js:5:37
`

Looking at the specified folder show that in 3.0.0 there is no index.js and in 2.5.1 there is.
That explains why the require '../../dialects' fails in 3.0.0

**Comment by kibertoad** [comment]
@puzzle-it-nu could you please send a PR for this?

**Comment by puzzle-it-nu** [comment]
I would but don't get why there is one single Typescript file in this project.
Looking at the history there is nothing that I can spot that has touched this file so I expect that the build should transpile this file but it seems it hasn't.

Will clone the repo and see if I can reproduce the build.

**Comment by Jiralite** [comment]
In Node.js 18.17.1, It's as easy to reproduce as:

```TypeScript
import "knex";
```

<details>
<summary>View stack trace</summary>
```xl
Error: Cannot find module '../../dialects'
Require stack:
- /Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/Knex.js
- /Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/index.js
- /Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/knex.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at l.default._resolveFilename (/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1777)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at <anonymous> (/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js:5:37)
    at Object.<anonymous> (/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js:57:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.S (/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/internal/config-resolver.js',
    '/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/knex-builder/Knex.js',
    '/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/lib/index.js',
    '/Users/jiralite/Documents/GitHub/thatskyapplication/caelus/node_modules/.pnpm/knex@3.0.0_pg@8.11.3/node_modules/knex/knex.js'
  ]
}
```
</details>

3.0.0 is unusable.

**Comment by kibertoad** [comment]
yeah, will unpublish. thank you for the report

**Comment by puzzle-it-nu** [comment]
> I would but don't get why there is one single Typescript file in this project. Looking at the history there is nothing that I can spot that has touched this file so I expect that the build should transpile this file but it seems it hasn't.
> 
> Will clone the repo and see if I can reproduce the build.

Cloning the repo and switching back to node-18 and running npm run build generates the missing index.js file so no idea why the package at npmjs.org is missing it

**Comment by kibertoad** [comment]
Something changed in the behaviour of newer npm, and it decided to ignore index.js because it was in gitignore. removing it from gitignore addressed the problem. I'll make the system more robust, but can you try 3.0.1 for now?

can't unpublish 3.0.0, someone is already depending on it :(

**Comment by Jiralite** [comment]
Not crashing on 3.0.1. Looks good to me!

**Comment by puzzle-it-nu** [comment]
Test run, good work 😀

**Comment by puzzle-it-nu** [comment]
Can be closed, I think

**Comment by adatta02** [comment]
I'm working on a private, forked version of Knex. 

I'm running into this issue when I try to include the forked version via github on node 18 or higher. It works fine on node 16+

On node 20, you can see it happening if you do:

```
git clone git@github.com:knex/knex.git
npm install
npm run build
npm pack
```

The archive at knex-3.1.0.tgz wont include lib/dialects/index.js even though the file exists on your system.
