### ISSUE TITLE
knex.transaction(...).finally is not a function

### ISSUE THREAD

**Issue by gaurav-jotwani** [knex/knex#3798]
Knex version: 0.20.14

I am upgrading knex from version 0.11.10 to 0.20.14 and I am observing an error:
`knex.transaction(...).finally is not a function`
Following is how I use finally:
```function transact(context, action) {
    if (context.transaction) {
      // Transaction is now available, use it
      return action();
    }

    // No transaction running now, create a new one
    return knex.transaction((tx) => {
      if (context.transaction) {
        throw new errors.ConcurrentTransactionError();
      }

      context.transaction = tx;

      return action();
    })
      .finally(() => {
      // Clear out the transaction from the context!
        context.transaction = null;
      });
  }

**Comment by elhigu** [comment]
Please follow the issue template. You didn't provide information about noder versions etc. Anyways I supporse you are using too old Node whose native Promise doesn't have `.finally` method.

**Comment by kibertoad** [comment]
@gaurav-jotwani Which Node version are you using?

**Comment by gaurav-jotwani** [comment]
Sorry about that I am actually using node v12.16

**Comment by gaurav-jotwani** [comment]
Also, the same works fine with knex 0.11.10 but not on 0.20.14 on the same version of node

**Comment by elhigu** [comment]
Have you overrided global promise with something?

```
Mikaels-MacBook-Pro:backend mikaelle$ node --version
v12.13.0
Mikaels-MacBook-Pro:backend mikaelle$  node

knex = require('knex')({client : 'pg', connection: 'postgres://localhost/knex_test'})
knex.transaction(async trx => {}).finally(() => console.log('FINALLY'))
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined
}
> FINALLY
```

Cannot reproduce.

**Comment by gaurav-jotwani** [comment]
I don't think I have. Plus everything works just fine when I just change the version to knex@0.11.10 and I have other pieces of code that use finally and they all work fine. For example: 
```const dbConfig = config.knex;
    const dbConnectionDetails = {
      client: dbConfig.client,
      connection: dbConfig.connection,
    };
    const db = knex(dbConnectionDetails);
    return db.raw('select 1').then(() => {
      logger.info('DB connection succeeded');
      const response = {
        status: constants.STATUS_OK,
      };
      return res.status(200).json(response);
    }).catch((err) => {
      logger.error('Error connecting to the DB.', err);
      next(new errors.BaseError(constants.HTTP_STATUSCODE_SERVICE_UNAVAILABLE, 'Error connecting to the DB'));
    }).finally(() => {
      logger.debug('Releasing DB connection');
      db.destroy();
    });

**Comment by kibertoad** [comment]
@gaurav-jotwani Could you submit a PR with a failing test that would reproduce your issue?

**Comment by kibertoad** [comment]
Wait.
@elhigu You use async function, so you definitely return a promise. @gaurav-jotwani does your `action()` return a promise?

**Comment by gaurav-jotwani** [comment]
yes the action() returns a promise. It looks something like this:
```knex.raw(sql, bindings)
      .insert(xRow)
      .returning(xMapper.fields)
      .then(xMapper.toEntity);
Also, the things works fine in knex@0.11.10 so if weren't returning a promise it should have failed in this version as well.

**Comment by kibertoad** [comment]
@gaurav-jotwani Old knex was using bluebird promises, new ones does not. That said, in newer Node.js all promises should support `finally`. I'm really curious to see what entity you are getting from your transaction. Which database are you using?

**Comment by gaurav-jotwani** [comment]
So I use postgres version 9.6 database. Entity is just an internal function that formats the data into the desired object format. It basically returns a json object.

**Comment by elhigu** [comment]
> @elhigu You use async function, so you definitely return a promise. @gaurav-jotwani does your action() return a promise?

Shouldn't matter since the promise returned from transaction is not related to the promise returned by the handler function.

**Comment by kibertoad** [comment]
@gaurav-jotwani OK, I debugged this thing and here's the thing: `knex.transaction` does not return you a promise, it returns you a transaction. It is `thenable` so can be used as a Promise-like, but it does not support `finally`. @maximelkin I think there was a discussion between you and @briandamaged regarding whether or not to have finally on it, and for some reason it was decided not to; is that correct?

If you want a full access to underlying promise, I think you need to do 
```
const trx = knex.transaction(...)
trx._promise.finally(...)
```

Probably this needs to be mentioned in UPGRADING notes.

**Comment by kibertoad** [comment]
It should also be super simple to add finally support for transactions in a similar way other promise-like methods are implemented:
```
  then(onResolve, onReject) {
    return this._promise.then(onResolve, onReject);
  }

  catch(onReject) {
    return this._promise.catch(onReject);
  }
```
Wonder if there are any reasons not to.

**Comment by elhigu** [comment]
> Cannot reproduce.

I actually had pretty old knex  (0.16) in that directory! I have to retest.

**Comment by gaurav-jotwani** [comment]
> @gaurav-jotwani OK, I debugged this thing and here's the thing: `knex.transaction` does not return you a promise, it returns you a transaction. It is `thenable` so can be used as a Promise-like, but it does not support `finally`. @maximelkin I think there was a discussion between you and @briandamaged regarding whether or not to have finally on it, and for some reason it was decided not to; is that correct?
> 
> If you want a full access to underlying promise, I think you need to do
> 
> ```
> const trx = knex.transaction(...)
> trx._promise.finally(...)
> ```
> 
> Probably this needs to be mentioned in UPGRADING notes.

Yes, I think this makes complete sense when I look at the issue I am facing.

**Comment by briandamaged** [comment]
Howdy!  Just catching up...

If I remember correctly, there was some mixin logic in place that was s'posed to inject the `finally(..)` method depending upon the version of node.  Lemme try to track that down...

**Comment by briandamaged** [comment]
So yeah: it looks like the mixin is still in place:

https://github.com/knex/knex/blob/82361d12c1383fdb5ecd8ff9fe72d2b9f1d8763c/lib/util/finally-mixin.js#L3-L8

https://github.com/knex/knex/blob/82361d12c1383fdb5ecd8ff9fe72d2b9f1d8763c/lib/transaction.js#L241

However, one other confusing detail: calling `knex.transaction(cb)` only returns a `Transaction` when `cb` returns a `Promise`.  Otherwise, it returns a `Transactor` instance  (Which is basically a function with various other functions injected into it).  So, it's possible that the `finally` method is missing from the `Transactor` instead of the `Transaction`.

**Comment by kibertoad** [comment]
@briandamaged Thank you for your research! That seems correct. Let me try to fix it.

**Comment by briandamaged** [comment]
Yeah... one of these days, I'll finally get back to refactoring this code.  I just unfortunately have not had much bandwidth in the last few weeks. 😅

**Comment by kibertoad** [comment]
@briandamaged I think problem is in mixin. If you are working in Node that out-of-the-box supports finally, it won't mixin anything into transaction.
Check this:
```
module.exports = Promise.prototype.finally ? noop : finallyMixin;
...
finallyMixin(Transaction.prototype);
```

So we need a separate method that forces mixin, I think.

**Comment by briandamaged** [comment]
@kibertoad : Ah -- yeah, I think I see what you mean.  The decision logic is wrong in this specific case.  It needs to be something more along the lines of: "If your version of node supports the `.finally(..)` method, then ensure that the `Transaction` class does as well".

**Comment by kibertoad** [comment]
@briandamaged So yeah, it kinda looks like check in `module.exports = Promise.prototype.finally ? noop : finallyMixin;` should be reversed, otherwise it doesn't seem to do any good ever.

**Comment by briandamaged** [comment]
@kibertoad : I don't think that's quite right, either.  The logic was intended as a way of handling Node 8 code.  If the code is using Node 8, then _don't_ add the `.finally(..)` polyfill.

I'll submit an MR in a few mins.  Which branch should the MR be based upon / merged into?

**Comment by kibertoad** [comment]
@briandamaged I can contribute a test for that effort:

test\unit\knex.js ->

```
  it('transactions support finally()', function(done) {
    const knex = Knex(sqliteConfig);

    const trx = knex.transaction(async (tx) => {
      return new Promise((resolve) => {
        resolve();
      });
    });

    trx.finally(() => {
      done();
    });
  });
```

master is good, I'll cherry-pick into 0.20 after merging

**Comment by elhigu** [comment]
btw. do we want also normal querybuilder to be able to be triggered with `.finally()` ?

```
> knex.select(1).finally(() => console.log('huh'))
Thrown:
TypeError: knex.select(...).finally is not a function
```

**Comment by briandamaged** [comment]
@elhigu : Good question.  IMO, the general rule should be: "If the version of Node you are using supports `.finally(..)`, then all of `knex`'s Promise-alikes should as well"

**Comment by kibertoad** [comment]
@briandamaged Does the mixin usage in lib\interface.js cover ground for that?

**Comment by briandamaged** [comment]
@kibertoad : My guess is that it prolly doesn't.

**Comment by elhigu** [comment]
> IMO, the general rule should be: "If the version of Node you are using supports .finally(..), then all of knex's Promise-alikes should as well"

Sounds good to me. Though it is hard to remember to make sure that our thenable interfaces always implements all the standard parts. As @kibertoad suggested would be great to have some common base implementation for knex thenables...

**Comment by briandamaged** [comment]
@elhigu : Yeah, I think that's what the intention was for the `finallyMixin(..)`.  But, it looks like we got our truth tables mixed up.  (No pun intended...)

**Comment by briandamaged** [comment]
@kibertoad  + @elhigu : k, just created an initial MR here:

#3800

**Comment by kibertoad** [comment]
Fix released in 0.20.15

**Comment by gaurav-jotwani** [comment]
Everything seems to be working fine in version 0.20.15 for me. Thank you everyone for the help!
