### ISSUE TITLE
Typescript doesn't compile with import Knex from 'knex' =>  v 0.21.1 

### ISSUE THREAD

**Issue by philipyoungg** [knex/knex#3897]
# Environment

Knex version: 0.21.1
Database + version: Postgres
OS: macOS

Select applicable template from below.
@lorefnon 
# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
Typescript doesn't compile when I use
`import Knex from 'knex'`
...but it works when I use
`const Knex = require('knex')`
but VSCode intelisense breaks as my `knex` instance become `any`—which is not helpful 
2. Error message
```
/Users/philipyoung/Sites/Website/blog-project/server/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/controllers/UserController.ts (56,10): Property 'from' does not exist on type 'QueryBuilder<any, DeferredKeySelection<any, never, true, { username: string; email: string; posts: any; }, false, {}, never>[]>'. (2339)
```

This is my `.tsconfig`
```
{
  "compilerOptions": {
    "lib": ["es5", "es6"],
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  }
}
```

**Comment by rijkvanzanten** [comment]
```ts
import Knex from 'knex';
```

seems to work fine on my end 👍

**Comment by philipyoungg** [comment]
@rijkvanzanten yep! Noticed that. Intelisense doesn't work though. 

> ...but it works when I use
const Knex = require('knex')
but VSCode intelisense breaks as my knex instance become any—which is not helpful

**Comment by rijkvanzanten** [comment]
![CleanShot 2020-07-01 at 16 58 12](https://user-images.githubusercontent.com/9141017/86290829-1479e500-bbbc-11ea-88bf-8b207b96e48d.png)


🤷

**Comment by philipyoungg** [comment]
@rijkvanzanten ah yeah sorry! My title was wrong. Edited it.
running `import Knex from 'knex'` 
makes Typescript didn't compile.

It shows this error.
```
/Users/philipyoung/Sites/Website/blog-project/server/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/controllers/UserController.ts (56,10): Property 'from' does not exist on type 'QueryBuilder<any, DeferredKeySelection<any, never, true, { username: string; email: string; posts: any; }, false, {}, never>[]>'. (2339)
```

**Comment by rijkvanzanten** [comment]
Are you sure this is caused by the import of knex, and not a wrong usage of the package further down the line? 

That error to me looks like you're trying to use `.from()` on an ill query in `src/controllers/UserController.ts` on line 56

**Comment by philipyoungg** [comment]
@rijkvanzanten I'm pretty sure that's not the issue, because import * as knex works without code change. 

Here's the code. 

![ADD9F2C0-512F-46A5-BEC3-3C016CE7DE38](https://user-images.githubusercontent.com/11477718/86497191-d989d400-bdaa-11ea-9b30-f3ce61651fc8.png)

**Comment by lorefnon** [comment]
The following are expected to work: 

```ts
import * as Knex from 'knex';

// Or

import Knex = require('knex');
```

Alternatively, you can also use `esModuleInterop: true` in tsconfig.json, and then: 

```ts
import Knex from 'knex';
```

Typescript's recommendations around typing commonjs modules are available [here](https://www.typescriptlang.org/docs/handbook/modules.html), which we follow.

**Comment by vitorhub182** [comment]
I have the same problem and thats works for me:
Before:
tsconfig.json: 
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "esModuleInterop": true,
        "target": "es6",
      }
}

After: 
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "esModuleInterop": true,
       }
}
