### ISSUE TITLE
Cannot find module '@vscode/sqlite3'

### ISSUE THREAD

**Issue by sombriks** [knex/knex#5001]
# Environment

Knex version: 1.0.2
Database + version: sqlite3 5.0.2
OS: windows 10 21h2 and mac os big sur 11.6.2, same problem
Node version: 14 lts

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

`npx knex --knexfile knexfile.cjs migrate:make schema_init`

2. Error message

```
Using environment: development
Knex: run
$ npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack:
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

see coomand line on bug explain

# Feature discussion / request

1. Explain what is your use case

it's a simple brand new project from scratch. it should simply work.

2. Explain what kind of feature would support this

3. Give some API proposal, how the feature should work

# Missing / erroneus documentation

Send issue to documentation repo, or fix it and send PR https://github.com/knex/documentation

# Questions about how to use knex

GitHub issues are for knex development. Please send questions how to use knex to
Stack Overflow or ask about it in gitter chat.

**Comment by kibertoad** [comment]
See https://github.com/knex/knex/blob/master/UPGRADING.md

You need to install `@vscode/sqlite3` dependency after migrating to 1.0.0+

**Comment by poacher2k** [comment]
@kibertoad : As mentioned in a comment on [another issue](https://github.com/knex/knex/issues/4858#issuecomment-1017522346), they have plans to delete the repo: https://github.com/microsoft/vscode-node-sqlite3/issues/16#issuecomment-1046059712
